# Generated by Django 3.0.7 on 2021-04-15 09:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('thapar_student', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('unwind_interested', models.BooleanField(default=True)),
                ('elevate_interested', models.BooleanField(default=True)),
                ('bootcamp_interested', models.BooleanField(default=True)),
            ],
        ),
    ]
